name: CI Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_project:
    runs-on: macos-latest
    steps:
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0'

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }} # Указываем текущую ветку
          fetch-depth: 0 # Получаем всю историю коммитов

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat
        run: swiftformat . --swiftversion 5.10

      - name: Build and Test
        run: |
          xcodebuild \
            -project UniWeather.xcodeproj \
            -scheme UniWeather \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=26.0.1' \
            test || exit 1

      - name: Check for changes
        id: changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Changes detected"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply SwiftFormat fixes [skip ci]"
          git fetch origin
          git checkout ${{ github.head_ref || github.ref_name }} # Переключаемся на текущую ветку
          git push origin ${{ github.head_ref || github.ref_name }}
